name: Open Source Software for Data Scientists
markdown: redcarpet
pygments: true
safe: true
lsi: false
timezone: America/New_York
google_analytics_ua: UA-49311172-1
permalink: none
full_url: http://oss4ds.com
exclude: [Gemfile, Gemfile.lock, README.md]
